const ACTIONS = {
    LOGIN : "LOGIN" , 
    GET_TOKEN : 'GET_TOKEN' ,
    GET_USER : 'GET_USER' ,
    GET_ALL_USERS : 'GET_ALL_USERS' ,
    GET_ALL_USERS_TWO : 'GET_ALL_USERS_TWO' ,
    GET_ALL_USERS_FOR_ALL : 'GET_ALL_USERS' ,
    GET_ALL_USERS_TWO_FOR_ALL : 'GET_ALL_USERS_TWO' ,
    GET_ALL_USERS_FOR_VISITORS : 'GET_ALL_USERS_FOR_VISITORS'
}

export default ACTIONS;